### ISSUE TITLE
sar_den is 0 if unknown

### ISSUE THREAD

**Issue by dericed** [FFmpeg/FFV1#109]
In FFmpeg sar_num/sar_den for unknown sar is `0/1` but the [spec at this section](https://github.com/FFmpeg/FFV1/blob/aadbb8c486a6cf688d18ee18a7e329ec527a8268/ffv1.md#sar_den) says "MUST be 0". As I read, it:

`sar_num  = 0 &&  sar_den  = 0` valid
`sar_num != 0 && sar_den != 0` valid
`sar_num  = 0 && sar_den != 0` not valid
`sar_num != 0 &&  sar_den  = 0` not valid

Which is wrong?
[ ] FFmpeg
[ ] FFV1 specification
[ ] my interpretation

I suggest requiring a denominator to be 0 is not ideal and that we be more flexible. Unknown sar could be communication by the numerator alone.

**Comment by JeromeMartinez** [comment]
As the goal in v0-v3 is to document the main implementation, I suggest we change the FFV1 spec fo v0-v3 for accepting 0/1 (only, or 0/any) and maybe change it in v4.

**Comment by michaelni** [comment]
FFmpeg is wrong, if it stores SAR=1/0 or 0/1. 0/1 equals 0, that is not achievable as an aspect ratio. 1/0 is not a finite number, 0/0 kind of means unknown. More so making 1/0 mean something else than 0/1 is problematic, as you get one from the other by simple rotation and that asymetry would be very illogic

**Comment by JeromeMartinez** [comment]
Issue is that some streams in the wild are with `0/1`, looks like it is the fallback in FFmpeg when DAR is unknown.
With e.g. `./ffmpeg -f lavfi -i testsrc -vframes 1 -c:v ffv1 -level 3 -vf setsar=0/2 a.mkv` ("2" is on purpose, for demonstrating that FFmpeg does something about SAR value), sar_den is 1, is it wanted?
Looks like I can not have sar_den of 0 with FFmpeg ("invalid string" if I try `0/0`).

I wonder:
- Should we flag streams created by FFmpeg as invalid when SAR is unknown? this is the situation with current spec, and I don't really like that.
- If not, which change in specs do you suggest?

**Comment by JeromeMartinez** [comment]
Bump on this, I would like to know the outcome in order to say what is wrong (FFmpeg or spec) with all people involved on FFV1 in sync about the issue, as some users don't understand that a stream created by current FFmpeg can be invalid, FFmpeg being "advertised" as the reference encoder/decoder for FFV1.

**Comment by dericed** [comment]
I suggest

```
### sar_num

`sar_num` specifies the sample aspect ratio numerator.  
Inferred to be 0 if not present.  
MUST be 0 if sample aspect ratio is unknown.

### sar_den

`sar_den` specifies the sample aspect ratio numerator.  
```

If `sar_num=0` then we already know the sar is unknown, so we don't need the same requirement for sar_den.

**Comment by JeromeMartinez** [comment]
> sar_den specifies the sample aspect ratio numerator.

Just seeing the ugly copy/paste with last word (shame on me), will fix it at the same time I patch this part.

**Comment by dericed** [comment]
ping to Jerome to fix copy/paste error

**Comment by dericed** [comment]
noting that the copy/paste error was fixed in https://github.com/FFmpeg/FFV1/commit/787fec68d712c8c5740e09f3a8e284f946542a3e
