### ISSUE TITLE
mark new release

### ISSUE THREAD

**Issue by dericed** [FFmpeg/FFV1#113]
Since https://github.com/FFmpeg/FFV1/commit/760bcfb73763ead0dfe24e05db75e4c32adec114 is merged, please mark a release before any further merges.
Since this is now both `draft-ietf-cellar-ffv1-02` and `draft-ietf-cellar-ffv1-v4-00` I suggest maybe `draft-ietf-cellar-ffv1-02_v4-00`. ¯\\_(ツ)_/¯

**Comment by michaelni** [comment]
done in https://github.com/FFmpeg/FFV1/releases/tag/draft-ietf-cellar-02
