### ISSUE TITLE
add citations to prerequisite documents

### ISSUE THREAD

**Issue by dericed** [FFmpeg/FFV1#14]
The https://github.com/FFmpeg/FFV1/blob/master/ffv1.md#introduction section refers to familiarity with concepts of Range coding and YCBCr colorspaces. I propose that we link to or name specific resources that can provide this familiarity.

**Comment by michaelni** [comment]
sure, do you have a patch or suggestions for which resources to link to ?

**Comment by dericed** [comment]
Not yet, for now I'm just trying to log issues for things to do. I'll look for a good resources on these issues that isn't behind a paywall.
