### ISSUE TITLE
"version \<= 3": Why the backslash?

### ISSUE THREAD

**Issue by pjotrek-b** [FFmpeg/FFV1#149]
In the definition of "quant_table_set_index_count" (slices), there's an escaped less-than-or-equal sign:
`1 + ( ( chroma_planes || version \<= 3 ) ? 1 : 0 ) + ( extra_plane ? 1 : 0 )`

Is that backslash after "version" intended?

**Comment by JeromeMartinez** [comment]
I guess I added a typo when I tried to backslash several other things.
Not intended.

**Comment by pjotrek-b** [comment]
I'll remove it then :)

**Comment by retokromer** [comment]
Is this still an open issue, @pjotrek-b?

**Comment by pjotrek-b** [comment]
Fixed in PR #148.
