### ISSUE TITLE
Typo: Slice Header in Slice Footer?

### ISSUE THREAD

**Issue by pjotrek-b** [FFmpeg/FFV1#150]
In "Slice Footer", it says:

> A Slice Footer provides information about slice size and (optionally) parity. The pseudo-code below describes the contents of the Slice **Header**.

The mentioned pseudo-code below only declares "SliceFooter()", so I guess it should be "Slice Footer" here insteadof "Slice Header"?

**Comment by JeromeMartinez** [comment]
Copy paste typo, right.

**Comment by dericed** [comment]
This issue can be closed. Fixed by https://github.com/FFmpeg/FFV1/commit/99a802edc5af9f2607f377fb6ae40631affbdee7.
