### ISSUE TITLE
Quant tables: reference decoder relies too much on reference encoder

### ISSUE THREAD

**Issue by JeromeMartinez** [FFmpeg/FFV1#169]
Reference encoder fills 4th & 5th quant tables with 0 if " -context 0" is used.
Reference decoder considers that 4th & 5th quant tables are 0-filled if the 128th field in 4th quant table is 0, instead of testing that all fields in 4th & 5th quant tables, for some quicker processing.

If another encoder puts 0 in the 128th field in 4th quant table and fills any of the other fields in 4th & 5th quant tables with non 0 value, the reference decoder would fail to decode a valid stream.

[Initially reported by @dwbuiten](https://twitter.com/daemon404/status/1177241544593686528).

So there is a mismatch between spec and reference decoder, but IMO the fix should be in the reference decoder, checking that all fields in 4th & 5th quant tables are 0-filled before using the quicker processing.
Using the FFV1 spec place because of the main issue is a mismatch between spec and reference decoder and it should not be forgotten, but I'll propose a patch for the reference decoder and the issue should be closed when the reference decoder has a fix (if everyone agrees that it is an issue with the reference decoder and not the spec). Or maybe there should be a warning in the spec about a compatibility issue with older decoders if one tries a weird quant table set?

**Comment by dwbuiten** [comment]
It should be possible to make the reference decoder work for all streams without losing any speed by precomputing the check (via `memcmp`) at the time the tables are read in, if I'm not mistaken?

It's probably worth a note in the spec too about compatability.

**Comment by JeromeMartinez** [comment]
> It should be possible to make the reference decoder work for all streams without losing any speed by precomputing the check (via memcmp) at the time the tables are read in, if I'm not mistaken?

It was my idea of patch proposal.

**Comment by dwbuiten** [comment]
Fixed in FFmpeg, as per the referenced commit.
