### ISSUE TITLE
document configuration record usage in mkv

### ISSUE THREAD

**Issue by dericed** [FFmpeg/FFV1#18]
When I run
`ffmpeg -f lavfi -i testsrc -pix_fmt yuv422p -c:v ffv1 -level 3 -g 1 -vframes 1 test.mkv`
and
`ffmpeg -f lavfi -i testsrc -pix_fmt yuv422p -c:v ffv1 -level 3 -g 1 -vframes 1 test.mov`
I see the content differs between mkv's CodecPrivate and mov's glbl atom.

mov stores the configuration record as `562B859E0033F59F4BC3EFABDB970D0B0242F7B163374A9505C43F5ABFD980FE198CD25D39CF244ED4EB`. In mkv it is the same but the data is prepended with other data on width, height, etc, so the mkv codec private used for the above example is:
`5200000040010000f000000001001800464656310084030000000000000000000000000000000000562b859e0033f59f4bc3efabdb970d0b0242f7b163374a9505c43f5abfd980fe198cd25d39cf244ed4eb`.

Is the different understood by the current mkv and/or ffv1 documentation? If not could ffv1 in mkv be added to ffv1.md as was done with avi, mp4 and nut.

**Comment by michaelni** [comment]
On Sat, Apr 23, 2016 at 05:22:55PM -0700, Dave Rice wrote:
> When I run
> `ffmpeg -f lavfi -i testsrc -pix_fmt yuv422p -c:v ffv1 -level 3 -g 1 -vframes 1 test.mkv`
> and
> `ffmpeg -f lavfi -i testsrc -pix_fmt yuv422p -c:v ffv1 -level 3 -g 1 -vframes 1 test.mov`
> I see the content differs between mkv's CodecPrivate and mov's glbl atom.
> 
> mov stores the configuration record as `562B859E0033F59F4BC3EFABDB970D0B0242F7B163374A9505C43F5ABFD980FE198CD25D39CF244ED4EB`. In mkv it is the same but the data is prepended with other data on width, height, etc, so the mkv codec private used for the above example is:
> `5200000040010000f000000001001800464656310084030000000000000000000000000000000000562b859e0033f59f4bc3efabdb970d0b0242f7b163374a9505c43f5abfd980fe198cd25d39cf244ed4eb`.
> 
> Is the different understood by the current mkv and/or ffv1 documentation? If not could ffv1 in mkv be added to ffv1.md as was done with avi, mp4 and nut.

wild guess, the mkv contains a AVI bitmapinfoheader ?
if thats the case see V_MS/VFW/FOURCC


[...]
-- 
Michael     GnuPG fingerprint: 9FF2128B147EF6730BADF133611EC787040B0FAB

Freedom in capitalist society always remains about the same as it was in
ancient Greek republics: Freedom for slave owners. -- Vladimir Lenin

**Comment by dericed** [comment]
You're right. It's bitmapinfoheader plus configuration record. I suppose if the Matroska spec defined V_FFV1 then a specific ffv1 codecprivate could be defined.

**Comment by dericed** [comment]
fixed in https://github.com/FFmpeg/FFV1/commit/6e9c3e0bf882929b85d9330cec6e692e6d5d30eb
