### ISSUE TITLE
few instances of lines too long

### ISSUE THREAD

**Issue by dericed** [FFmpeg/FFV1#198]
The process that generates the RFC doesn't line-wrap code blocks so there are a few instances where the current ffv1.md causes lines that exceed 72 characters.

The first two lines here exceed by two characters:
```
      pseudo-code                                                   | type
      --------------------------------------------------------------|-----
      void put_symbol(RangeCoder *c, uint8_t *state, int v, int \   |
      is_signed) {                                                  |
```

and the first two lines here (also by two characters):

```
      pseudo-code                                                   | type
      --------------------------------------------------------------|-----
      Parameters( ) {                                               |
          version                                                   | ur
```

**Comment by JeromeMartinez** [comment]
@dericed I checked the current version and all parts with "| type" stuff are 68 character long, what would be the difference between the 2 lines which exceed by to characters and the other lines/parts?

**Comment by dericed** [comment]
fixed in https://github.com/FFmpeg/FFV1/pull/196
