### ISSUE TITLE
[v4] slices

### ISSUE THREAD

**Issue by retokromer** [FFmpeg/FFV1#233]
There are some problems with the way slices are managed in versions 0 to 3, which in my opinion should be addressed in version 4.

E.g. with a 1536 = 2 ^ 9 x 3 pixel height image (i.e. a multiple of 4), I got the error message:

![Capture d’écran 2020-09-25 à 15 31 34](https://user-images.githubusercontent.com/3246607/94276877-1ba95880-ff49-11ea-882c-2b16ceeded48.png)

I guess, it would be easier to work with slices_x and slices_y values rather than to use a single value.

**Comment by dwbuiten** [comment]
This is not a spec limitation, but an encoder limitation AFAICT.

**Comment by retokromer** [comment]
There is a [discussion](https://github.com/FFmpeg/FFV1/issues/231#issuecomment-697579247) to focus the pseudo-code in the specifications on the decoder. I guess this should be specified there.

**Comment by dericed** [comment]
I don't understand what the problems are or what the fix would be. For ffv1 with version >=3 the values for slice_x and slice_y are independent values within the slice header and they don't need to be the same value. If the version is <=3 then there is no slice header and thus no slice_x and slice_y, so the non-existent values are the same (I guess).

At any rate, if you're discussing an issue that is about a particular ffv1 decoder and not the specification then the issue should be closed.

**Comment by dwbuiten** [comment]
I agree, this issue is specific only to the implementation of the FFV1 encoder in ffmpeg, and is unrelated any restrictions in the spec.

**Comment by retokromer** [comment]
>this issue is specific only to the implementation of the FFV1 encoder in ffmpeg

I see, closing.
