### ISSUE TITLE
reading through section 3.8.1.1

### ISSUE THREAD

**Issue by dericed** [FFmpeg/FFV1#258]
To resolve the last open issues of the spec, I'm trying to read through and understand Section 3.8.1.1 and I get stuck fairly soon. Nudges to @michaelni, @dwbuiten, @JeromeMartinez.

The introductory text is:
> To encode binary digits efficiently a Range coder is used.  C_(i) is
   the i-th Context.  B_(i) is the i-th byte of the bytestream. b_(i) is
   the i-th Range coded binary value, S_(0, i) is the i-th initial
   state.  The length of the bytestream encoding n binary symbols is
   j_(n) bytes.

Then a formula is shown:

`r_(i) = floor( ( R_(i) * S_(i, C_(i)) ) / 2 ^ 8 )`

The formula has this caption, which I wrote by trying to guess the meaning:
> Figure 11: A formula of the read of a binary value in Range Binary mode.

Here are my questions based on reading this part:

- How does the formula relate, if at all, to the introductory text? Is the formula used to "encode binary digits efficiently"?
- What is `r_(i)`? A lowercase `r` is used in Section 3.7.2 to signify `red`, but from context that doesn't match. I suggest `r_(i)` needs some definition local to this section? Would reading the normative text of range-coding show me what `r_(i)` means?
- What is `R_(i)`? Also undefined within this document? Down in Figure 15 `R_(0)` is referenced as `Figure 15: The initial value for "Range".` which is a caption I wrote as a guess. Is this accurate? Is `R_(i)` the same as what is referred to as `range` in this example of [range-coding](https://en.wikipedia.org/wiki/Range_encoding#Example).
- `S_(0,i)` and `C_(i)` are defined as the `state` and `context`, which is helpful but another sentence that relates these terms as components of range-coding would be helpful.

I'd welcome any discussion and hope to use information gathered to write a patch.

**Comment by dericed** [comment]
👀

**Comment by michaelni** [comment]
> Here are my questions based on reading this part:
> 
> * How does the formula relate, if at all, to the introductory text? Is the formula used to "encode binary digits efficiently"?

I do not understand the question


> * What is `r_(i)`? A lowercase `r` is used in Section 3.7.2 to signify `red`, but from context that doesn't match. I suggest `r_(i)` needs some definition local to this section? Would reading the normative text of range-coding show me what `r_(i)` means?
> * What is `R_(i)`? Also undefined within this document? Down in Figure 15 `R_(0)` is referenced as `Figure 15: The initial value for "Range".` which is a caption I wrote as a guess. Is this accurate? Is `R_(i)` the same as what is referred to as `range` in this example of [range-coding](https://en.wikipedia.org/wiki/Range_encoding#Example).

R_(i) is the range at symbol i, that is then split in 2 ranges one in case the ith symbol is a 0 and one in case its a 1. r_(i)  is the range for the case its a 1 R_(i) - r_(i)  for the 0 case


> * `S_(0,i)` and `C_(i)` are defined as the `state` and `context`, which is helpful but another sentence that relates these terms as components of range-coding would be helpful.

Do you understand what is meant by state and context ? iam asking as i do not know if that needs more verbose explaning or something else ? 
Its not clear to me what exactly needs more explaning just that something needs more

**Comment by dericed** [comment]
Thanks @michaelni, this is really helpful and I'm hoping to send a PR soon. In the meanwhile I have a few more questions.

Please correct any of my understanding here if wrong or could be better clarified.

- IIUC, in the context of the range coder, a `State` is the period from which the Range coder state variables were initialized until the next initialization (such as at a keyframe) or the end of the coding.

- Regarding `Range coder state variables` can we denote these values clearly? I see `R_(0)` and `L_(0)`, are there others that could be considered `Range coder state variables`? `j_(0)`?

- What is `t_(i)`? It is used in several formulae but what does it represent?

- What does `k` represent, as in `S_(i + 1, k) = S_(i, k) <== C_(i) != k`?

- Any objection if I change the direction of the implications from `<==` to `==>`? I think the `==>` might be more "readable", such as `C_(i) != k ==> S_(i + 1, k) = S_(i, k)`.

**Comment by michaelni** [comment]
> Thanks @michaelni, this is really helpful and I'm hoping to send a PR soon. In the meanwhile I have a few more questions.
> 
> Please correct any of my understanding here if wrong or could be better clarified.
> 

> * IIUC, in the context of the range coder, a `State` is the period from which the Range coder state variables were initialized until the next initialization (such as at a keyframe) or the end of the coding.
> * Regarding `Range coder state variables` can we denote these values clearly? I see `R_(0)` and `L_(0)`, are there others that could be considered `Range coder state variables`? `j_(0)`?

for the range coder each context (for examle a context may be a specific black&white checkered background surrounding the to be coded sample) has a state for each binary symbol that is coded. This state can change each time a symbol is coded with that context. all other states are unchanged. so these states generally change multiple times in a frame. 
This is different from the "state" of the range coder which would include range / low / position in bitstream. I think we never use the term "state" to refer to that more encompassing thing and i think we should use different terms for the 2 to avoid confusion

> * What is `t_(i)`? It is used in several formulae but what does it represent?

t as in "temporary"


> * What does `k` represent, as in `S_(i + 1, k) = S_(i, k) <== C_(i) != k`?

k is the same concept as in for example
for all k in N for which k has no divisors except itself and 1, k is a prime


> * Any objection if I change the direction of the implications from `<==` to `==>`? I think the `==>` might be more "readable", such as `C_(i) != k ==> S_(i + 1, k) = S_(i, k)`.

whatever people prefer.

**Comment by dericed** [comment]
Thanks @michaelni. Based on the main branch I'll update my reading notes and questions.

I know understand the introduction to section 3.8.1.1 better and the definition list of values. The following paragraph describes the initialization of several variables which are then expressed in Figures 11 through 13.

At this point though, I think an additional few sentence would be helpful between Figures 13 (the last of the initialization formula) and Figure 14. So here's my questions to try to understand what could help here?

- Of figures 14 through 20, could they be intuitively grouped together? What would those groups be?

- Do I understand correctly that figures 14 through 20 are relevant to reading (decoding) but not to writing (encoding)?

- Figure 15 is the only place where `<==>` is used with `b_(i) = 0 <==> L_(i) < R_(i) - r_(i)` and `b_(i) = 1 <==> L_(i) >= R_(i) - r_(i)`. Is it possible that `b_(i) = 0` and `L_(i) >= R_(i) - r_(i)`? Am curious why this formula uses `<==>` rather than `==>`.

- Could you suggest a definition for `l_(i)`?

- In the Figure 18 caption `A pseudo-code description of the initial states in Range Binary mode.` is 'initial states' the right word or should this be 'initialization of Range coder state variables'?

**Comment by michaelni** [comment]
> At this point though, I think an additional few sentence would be helpful between Figures 13 (the last of the initialization formula) and Figure 14. So here's my questions to try to understand what could help here?
> 

Something like: The following equations define how the range coder variables evolve as it reads or writes symbols


> * Of figures 14 through 20, could they be intuitively grouped together? What would those groups be?

14: positioning the range split based on the state
15: linking the decoded symbol, updated state and updated range
16: carrying over the unchanged states
17: linking the range coder with the bytestream read/write


> * Do I understand correctly that figures 14 through 20 are relevant to reading (decoding) but not to writing (encoding)?

I would not say that. That to me sounds like pi is about converting the circumference of a circle to its radius but not its radius to its circumference


> * Figure 15 is the only place where `<==>` is used with `b_(i) = 0 <==> L_(i) < R_(i) - r_(i)` and `b_(i) = 1 <==> L_(i) >= R_(i) - r_(i)`. 

> Is it possible that `b_(i) = 0` and `L_(i) >= R_(i) - r_(i)`? Am curious why this formula uses `<==>` rather than `==>`.

no, the subrange we are in is tied to the symbol that comes out or goes into the coder, the same way a read bit from a bitstream would be tied to the symbol a huffman de/encoder would in/output


> * Could you suggest a definition for `l_(i)`?

The L and l are the Low value, the difference is the location in the computation. One is before decoding a symbol the other afterwards, one before potentially reading the next byte one after. The relation of L and l is similar to R, r and t


> * In the Figure 18 caption `A pseudo-code description of the initial states in Range Binary mode.` is 'initial states' the right word or should this be 'initialization of Range coder state variables'?

"initialization of Range coder variables" sounds better considering the existing use of terms i think.

**Comment by JeromeMartinez** [comment]
It looks like this issue can be closed (https://github.com/FFmpeg/FFV1/pull/260 is merged).

**Comment by mcr** [comment]
please close.
