### ISSUE TITLE
clarify assignment operators

### ISSUE THREAD

**Issue by dericed** [FFmpeg/FFV1#27]
The language of assignment operators is currently like:

> `a++`         is equivalent to a = a + 1.

However, either:

> `a++`         is equivalent to `a := a + 1`.

or
> `a++`         is equivalent to `a` is assigned `a + 1`.

would be more clear.

**Comment by retokromer** [comment]
I suggest the less verbose `a := a + 1`.

**Comment by JeromeMartinez** [comment]
`=` is defined as `a = b means a is assigned b.`
`:=` is not defined and would be redundant with the definition of `=`.
"is assigned to" is also redundant with the definition of `=`.

So I don't see the difference.
would you like 

> `a++` is equivalent to `a = a + 1.`

**Comment by retokromer** [comment]
May I disagree? `a = a + 1` is a mathematical nonsense and therefore `:=` was introduced.

**Comment by JeromeMartinez** [comment]
Introduced by?

We decided to use the C notation, and `=` is used for assignment in C.
We need a more global decision that for this part of the spec we agree not to use C convention (and change lots of parts in the specs).

I am not against changing to `:=`, this is just a more intrusive change in the way we do the spec (~40 places in the spec to be changed, no more "like C")

**Comment by retokromer** [comment]
I have to check in my noted who introduced it, I cannot remember it at this moment.

Yet, then, I suggest the more verbose `a` is assigned `a + 1` which is correct.

**Comment by dericed** [comment]
I agree with @JeromeMartinez in https://github.com/FFmpeg/FFV1/issues/27#issuecomment-270168500 and see that `a = b` (assignment) and `a == b` (equals) are already well defined, but I think using the more verbose `a is assigned a + 1` in https://github.com/FFmpeg/FFV1/blob/master/ffv1.md#assignment-operators would be more clear.

**Comment by retokromer** [comment]
@JeromeMartinez According to Wikipedia is the 1st Algol: https://en.wikipedia.org/wiki/Assignment_(computer_science)
