### ISSUE TITLE
explain convention of documenting component structures

### ISSUE THREAD

**Issue by dericed** [FFmpeg/FFV1#35]
In https://github.com/FFmpeg/FFV1/blob/master/ffv1.md#conventions it references the `C standard` for operators and order of precedence, but `C` is also used to document structures within FFV1, such as in https://github.com/FFmpeg/FFV1/blob/master/ffv1.md#configuration-record, https://github.com/FFmpeg/FFV1/blob/master/ffv1.md#frame, and https://github.com/FFmpeg/FFV1/blob/master/ffv1.md#slice. I think it could be made more clear that these sections are in `C` by referencing this usage in the Conventions section.

**Comment by JeromeMartinez** [comment]
we use "if", "else" and so on as in C standard, but the structure is not C, so we need a dedicated paragraph about it.

**Comment by dericed** [comment]
@JeromeMartinez can you draft such a paragraph?

**Comment by dericed** [comment]
I found some IETF documentation that pertains to this issue at https://www.ietf.org/iesg/statement/pseudocode-guidelines.html (see references to `pseudocode`).

**Comment by dericed** [comment]
closed via https://github.com/FFmpeg/FFV1/commit/68f6d1e2743df5f8037d4dfa724d44281272656a
