### ISSUE TITLE
define len and len_count

### ISSUE THREAD

**Issue by dericed** [FFmpeg/FFV1#41]
Within the Quantization Tables section it uses `len` and `len_count[ i ][ j ]`. I don't see these terms in any other section and they don't seem to be assigned to any value. I'm unclear where to go to get further detail of their meaning. Should they be defined in this section or get a reference?

**Comment by retokromer** [comment]
I suggest to define.

**Comment by dericed** [comment]
Not sure if I understand the intent enough to define. Is `len` the length of the `slice`? I presume that len_count is a counter but am not sure how to explain the two arguments used in it, such as `len_count[ i ][ j ]`.

**Comment by JeromeMartinez** [comment]
`len` and `len_count[ i ][ j ]` are temporary values used to simplify the pseudo code, and are not used elsewhere (they are not kept by the decoder during decoding).
Is it fine for you if I say something like "`len ` is a temporary value used in QuantizationTable(i, j, scale) only and is not used elsewhere"?

**Comment by JeromeMartinez** [comment]
(sorry, was willing to talk about `len_count[ i ][ j ]` only as `len` was already described)

**Comment by dericed** [comment]
resolved by https://github.com/FFmpeg/FFV1/pull/103
