### ISSUE TITLE
inconsistency in the context equation

### ISSUE THREAD

**Issue by dericed** [FFmpeg/FFV1#51]
The context section says:
> The quantized sample di erences L-l, l-tl, tl-t, t-T, t-tr are used as context:

but then lists a equation that doesn't use `t-T` but does use `T-t`.

**Comment by retokromer** [comment]
If I understand correctly, then `T-t` is the correct reading, but certainly @michaelni can answer this better as I can do.

**Comment by JeromeMartinez** [comment]
This is `T-t` in code, so the correct one.
I suggest to replace:
`The quantized sample differences L-l, l-tl, tl-t, t-T, t-tr are used as context:`
by
`Context is:`

formulas, even some small ones like differences, should not be repeated.

**Comment by dericed** [comment]
I'll fix this one after https://github.com/FFmpeg/FFV1/pull/50 to avoid the conflict.

**Comment by dericed** [comment]
fixed in https://github.com/FFmpeg/FFV1/commit/d372bdc6b451b349c6e4170ff502ca99852c677e
