### ISSUE TITLE
standardize "color space" vs "colorspace"

### ISSUE THREAD

**Issue by dericed** [FFmpeg/FFV1#54]
both are used

**Comment by ablwr** [comment]
Is there a preference?

**Comment by dericed** [comment]
https://tools.ietf.org/html/rfc6386 seems to prefer "color space", I think I would too.

**Comment by dericed** [comment]
@ablwr resolved this in https://github.com/FFmpeg/FFV1/commit/90aea8bdc680a0e47f48faf7e042c0171db9a494.
