### ISSUE TITLE
version 02 release

### ISSUE THREAD

**Issue by dericed** [FFmpeg/FFV1#59]
I suggest marking a 02 release so that the file can be updated in the cellar documents section. Can you please mark a release for `draft-niedermayer-cellar-ffv1-02`.

**Comment by michaelni** [comment]
done
https://github.com/FFmpeg/FFV1/releases/tag/draft-n-cellar-02

**Comment by dericed** [comment]
sending a bit too late, but https://github.com/FFmpeg/FFV1/pull/60 is related
